# Generated by Django 3.2.25 on 2025-01-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250120_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ps_avl',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='xbaox_avl',
            field=models.IntegerField(default=10),
        ),
    ]
