# Generated by Django 3.2.25 on 2025-01-27 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_bookpc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='controllers',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ps_avl',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='xbaox_avl',
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('console_id', models.AutoField(primary_key=True, serialize=False)),
                ('console_category', models.CharField(choices=[('XBOX', 'Xbox'), ('PS', 'PlayStation')], max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('rental_start_date', models.DateTimeField(blank=True, null=True)),
                ('rental_return_date', models.DateTimeField(blank=True, null=True)),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.console'),
        ),
    ]
